version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: setup
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make setup

      - run:
          name: lint
          command: |
            . .env/bin/activate
            make lint

      - run:
          name: test
          command: |
            . .env/bin/activate
            make test
  docker-build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: make build
      - run:
          name: Test builded image
          command: make docker-test


workflows:
  version: 2

  main:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v.*/

  test-dev:
    jobs:
      - docker-build:
          context: org-dev


  nightly:
    jobs:
      - build:
          context: org-global
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
