version: 2
jobs:  
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "d0:65:bc:79:9d:bd:34:cb:aa:76:c6:62:af:12:73:4c"
      - run:
          name: setup
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make setup

      - run:
          name: lint
          command: |
            . .env/bin/activate
            make lint

      - run:
          name: test
          command: |
            . .env/bin/activate
            make test

